version: '3'
services:
  app:
    build:
      context: ./
    volumes:
      - .:/var/www/html
    ports:
      - "80:80"
      - "433:433"
    environment:
      - APP_ENV=production
      - APP_DEBUG=true