version: '3'
services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
      
    volumes:
      - .:/var/www/html
    ports:
      - "80:80"
      - "433:433"
    container_name: app
    restart: unless-stopped
    tty: true

    environment:
      - APP_ENV=production
      - APP_DEBUG=true
    networks:
      - evsnet
    depends_on:
      - mysql
  mysql:
      image: 'mysql/mysql-server:8.0'
      container_name: db
      restart: unless-stopped
      tty: true
      ports:
          - '${FORWARD_DB_PORT:-3306}:3306'
      environment:
          MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
          MYSQL_ROOT_HOST: "%"
          MYSQL_DATABASE: '${DB_DATABASE}'
          MYSQL_USER: '${DB_USERNAME}'
          MYSQL_PASSWORD: '${DB_PASSWORD}'
          MYSQL_ALLOW_EMPTY_PASSWORD: 1
          SERVICE_TAGS: dev
          SERVICE_NAME: mysql
      volumes:
        - mysqldata:/var/lib/mysql/
        - ./docker/mysql/my.cnf:/etc/mysql/my.cnf
      networks:
        - evsnet
#Docker Networks
networks:
  evsnet:
    driver: bridge
#Volumes
volumes:
  mysqldata:
    driver: local